name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Este paso descarga el código de tu repositorio

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'  # Asegúrate de que coincide con tu versión de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala las dependencias del proyecto

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Aquí se usa el secret que creaste
        run: |
          sonar-scanner \
          -Dsonar.projectKey=tu-project-key \
          -Dsonar.organization=tu-organization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
